project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
    - "LPS_lidR_LiDAR_Intro.qmd"
    - "!R/"

website:
  title: "lidRtutorial"
  favicon: "img/logo.png"
  site-url: https://r-lidar.github.io/lidRbook/
  navbar:
    search: true
    background: dark
    collapse-below: lg
    type: light
    logo: "img/logo.png"
    left:
      - text: "0-PREPROCESS"
        href: "00_preprocess.qmd"
      - text: "1-LAS"
        href: "01_read.qmd"
      - text: "2-DTM"
        href: "02_dtm.qmd"
      - text: "3-CHM"
        href: "03_chm.qmd"
      - text: "4-METRICS"
        href: "04_metrics.qmd"
      - text: "5-LASCATALOG"
        href: "05_catalog.qmd"
      - text: "6-ROI"
        href: "06_roi.qmd"
      - text: "7-ABA"
        href: "07_aba.qmd"
      - text: "8-ITS"
        href: "08_its.qmd"
      - text: "9-SOLUTIONS"
        href: "09_solutions.qmd"
  search: 
    location: navbar
    type: overlay

lightbox: true

format:
  html:
    theme: [simple, assets/styles.scss]
    css: [assets/custom.css]
    toc: true
    toc-depth: 4
    code-overflow: wrap

editor: source